kind: pipeline
name: default

steps:
  - name: install
    image: golang:1.13
    commands:
      - go mod download
      - go mod verify
      - go mod tidy
    volumes:
      - name: gopath
        path: /go

  - name: generate
    image: golang:1.13
    commands: ["go generate ./..."]
    volumes:
      - name: gopath
        path: /go

  - name: diff
    image: alpine/git
    commands:
      - |
        if ! git diff --exit-code HEAD; then
          echo "Generated files differ from commit." >&2 && \
          exit 1
        fi

  - name: lint
    image: stevenxie/golinter
    settings:
      revive_config: .revive.toml
    environment:
      CGO_ENABLED: '0'
      GOPROXY: &goproxy https://goproxy.io
    volumes:
      - name: gopath
        path: /go

  - name: info
    image: alpine/git
    commands:
      - git fetch --tags
      - git describe --tags 2> /dev/null | cut -c 2- > /info/version
      - git rev-parse HEAD 2> /dev/null > /info/commit
      - git rev-parse --abbrev-ref HEAD 2> /dev/null > /info/branch
      - head -1 < go.mod | awk '{print $2}' 2> /dev/null > /info/module
      - tail -n +1 /info/*
    volumes:
      - name: info
        path: /info

  - name: build_binary
    image: golang:1.13
    commands:
      - export MOD="$(cat /info/module)"
      - |
        [ -s /info/version ] && \
          export VER="$(cat /info/version)" || \
          export VER="$(cat /info/commit)"
      - export LDFLAGS="-X $${MOD}/internal/info.Version=$${VER}"
      - echo "LDFLAGS=$${LDFLAGS}" 1>&2
      - go test -ldflags "$LDFLAGS" -race ./...
      - export CGO_ENABLED=0
      - go build -trimpath -ldflags "$LDFLAGS" -o ./dist/ ./cmd/...
    environment:
      GOPROXY: *goproxy
    volumes:
      - name: gopath
        path: /go
      - name: info
        path: /info

  - name: build_image
    image: stevenxie/kaniko-drone
    settings:
      repo: stevenxie/api
      tags:
        - |
          $([ $DRONE_BUILD_EVENT != tag ] && \
            printf '%s-%s' $(cat /i/branch | tr / -) $(cat /i/commit) || true)
        - |
          $([ $DRONE_BUILD_EVENT != pull_request ] && \
            [ $(cat /i/branch) == master ] && \
            echo latest || true)
        - |
          $([ $DRONE_BUILD_EVENT != pull_request ] && \
            ([ $DRONE_BUILD_EVENT == tag ] || \
             [ $(cat /i/branch) == master ]) && \
             cat /i/version || true)
      username: stevenxie
      password:
        from_secret: docker_pass
    volumes:
      - name: info
        path: /i


volumes:
  - name: gopath
    temp: {}
  - name: info
    temp: {}
