## This docker-compose config file is used to define build processes for the
## images in this repository, and for development deployment.
##
## It is not meant for use in production deployments. See the deployment/
## directory for production deployment configurations.

version: "3.4"

services:
  api:
    image: "stevenxie/api:${VERSION}"
    build:
      context: .
      args:
        BUILD_VERSION: "${VERSION}"
      cache_from:
        - stevenxie/api:latest
        - alpine:3.8
    container_name: api
    environment:
      - GOENV=development
    # env_file:
    #   - ./.env
    volumes:
      - type: bind
        source: ./config.yml
        target: /etc/api/config.yml
    networks:
      - public
    ports:
      - "3000:3000" # for development

  api_test:
    image: "stevenxie/api-tester"
    build:
      context: .
      dockerfile: test.Dockerfile
      cache_from:
        - stevenxie/api-tester:latest
        - golang:1


networks:
  public:
