## This docker-compose config file is used to define build processes for the
## images in this repository, and for development deployment.
##
## It is not meant for use in production deployments. See the deployment/
## directory for production deployment configurations.

version: "3.4"

services:
  api:
    image: "stevenxie/api:${VERSION}"
    build:
      context: .
      args:
        BUILD_VERSION: "${VERSION}"
      cache_from:
        - stevenxie/api:latest
        - alpine:3.8
        - golang:alpine
    container_name: api
    environment:
      - GO_ENV=development
    networks:
      - public
    ports:
      - "3000:3000" # for development


networks:
  public:
