---

apiVersion: v1
kind: Service

metadata:
  name: api
  namespace: default

spec:
  type: ClusterIP
  selector:
    app: api
    tier: backend
    track: stable
  ports:
    - name: api
      protocol: TCP
      port: 3000
