{{- $config := .Values.config -}}
{{- if not $config -}}
  {{- /* TODO: 'required' doesn't recognize empty maps */ -}}
  {{- required ".Values.config is required" .HACK -}}
{{- end -}}

apiVersion: v1
kind: ConfigMap

metadata:
  name: {{ include "api.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "api.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "api.chart" . }}

data:
  config.yml: |
    {{- $config | toYaml | nindent 4 }}
