{{- $name := include "api.name" . -}}
{{- $fullName := include "api.fullname" . -}}
{{- $component := .Values -}}
{{- $deploy := $component.deployment -}}
{{- $image := $component.image -}}
{{- define "deploy-labels" -}}
  {{- range $key, $val := .Values.deployment.labels }}
    {{- $key }}: {{ $val | quote }}
  {{- end }}
{{- end -}}
{{- $labels := include "deploy-labels" . -}}

apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ $fullName }}
  labels:
    app.kubernetes.io/name: {{ $name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "api.chart" . }}
    {{- $labels | nindent 4 }}

spec:
  replicas: {{ $deploy.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ $name }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      {{- $labels | nindent 6 }}
  strategy:
    {{- toYaml $deploy.strategy | nindent 4 }}
  minReadySeconds: {{ $deploy.minReadySeconds }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ $name }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        {{- $labels | nindent 8 }}
    spec:
      containers:
        - name: api
          image: "{{ $image.repository }}:{{ $image.tag }}"
          imagePullPolicy: {{ $image.pullPolicy }}
          envFrom:
            - secretRef:
                name: {{ $fullName }}
          volumeMounts:
            - name: config
              mountPath: /etc/api
          ports:
            - name: api
              containerPort: {{ $deploy.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: api
              initialDelaySeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: api
              initialDelaySeconds: 10
          {{- with $component.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ $fullName }}
      {{- with $component.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $component.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $component.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
