{{- $name := include "api.name" . -}}
{{- $fullName := include "api.fullname" . -}}
{{- $ingress := .Values.ingress -}}
{{- $varnish := .Values.varnish -}}

{{- if $ingress.enabled -}}
apiVersion: extensions/v1beta1
kind: Ingress

metadata:
  name: {{ $fullName }}
  labels:
    app.kubernetes.io/name: {{ $name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "api.chart" . }}
  {{- range $key, $val := $ingress.labels }}
    {{ $key }}: {{ $val | quote }}
  {{- end }}
  {{- with $ingress.annotations }}
  annotations:
  {{- range $key, $val := . }}
    {{ $key }}: {{ $val | quote }}
  {{- end }}
  {{- end }}

spec:
{{- with $ingress.tls }}
  tls:
  {{- range . }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
    - host: {{ $ingress.host | quote }}
      http:
        paths:
        {{- with $ingress.path }}
          - path: {{ . }}
            backend:
        {{- else }}
          - backend:
        {{- end }}
            {{- if $varnish.enabled }}
              serviceName: {{ include "varnish.fullname" . }}
              servicePort: varnish
            {{- else }}
              serviceName: {{ include "api.fullname" . }}
              servicePort: api
            {{- end }}
{{- end }}
