{{- $name := include "api.name" . -}}
{{- $fullName := include "api.fullname" . -}}
{{- $component := index .Values "jobserver-ui" -}}
{{- $service := $component.service -}}

{{- if $component.enabled -}}
apiVersion: v1
kind: Service

metadata:
  name: {{ $fullName }}-jobserver-ui
  labels:
    app.kubernetes.io/name: {{ $name }}
    helm.sh/chart: {{ include "api.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}

spec:
  type: {{ $service.type }}
  ports:
    - name: http
      protocol: TCP
      port: {{ $service.port }}
  selector:
    app.kubernetes.io/name: {{ $name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
