{{- $name := include "api.name" . -}}
{{- $fullName := include "api.fullname" . -}}

{{- $component := index .Values "jobserver-ui" -}}
{{- $image := $component.image -}}
{{- $deploy := $component.deployment -}}

{{- if $component.enabled -}}
apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ $fullName }}-jobserver-ui
  labels:
    app.kubernetes.io/name: {{ $name }}-jobserver-ui
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "api.chart" . }}

spec:
  replicas: {{ $component.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ $name }}-jobserver-ui
      app.kubernetes.io/instance: {{ .Release.Name }}
  strategy:
    {{- toYaml $deploy.strategy | nindent 4 }}
  minReadySeconds: {{ $deploy.minReadySeconds }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ $name }}-jobserver-ui
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: jobs
          image: "{{ $image.repository }}:{{ $image.tag }}"
          imagePullPolicy: {{ $image.pullPolicy }}
          env:
            - name: NAMESPACE
              value: {{ $component.namespace  }}
            - name: REDIS_ADDR
              value: {{ $component.redisAddr | quote }}
          ports:
            - name: http
              containerPort: 80
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          {{- with $component.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with $component.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $component.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $component.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
