{{- $name := include "api.name" . -}}
{{- $fullName := include "api.fullname" . -}}
{{- $component := .Values.jobserver -}}
{{- $image := $component.image -}}
{{- $deploy := $component.deployment -}}

{{- if $component.enabled -}}
apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ $fullName }}-jobserver
  labels:
    app.kubernetes.io/name: {{ $name }}-jobserver
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "api.chart" . }}

spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ $name }}-jobserver
      app.kubernetes.io/instance: {{ .Release.Name }}
  strategy:
    {{- toYaml $deploy.strategy | nindent 4 }}
  minReadySeconds: {{ $deploy.minReadySeconds }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ $name }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: jobs
          image: "{{ $image.repository }}:{{ $image.tag }}"
          imagePullPolicy: {{ $image.pullPolicy }}
          envFrom:
            - secretRef:
                name: {{ $fullName }}
          volumeMounts:
            - name: config
              mountPath: /etc/api
          {{- with $component.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ $fullName }}
      {{- with $deploy.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $deploy.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $deploy.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
