{{- $name := include "jobs-ui.name" . -}}
{{- $fullName := include "jobs-ui.fullname" . -}}
{{- $component := index .Values "jobserver-ui" -}}
{{- $image := $component.image -}}
{{- $deploy := $component.deployment -}}
{{- define "jobs-ui-deploy-labels" -}}
  {{- range $key, $val := index .Values "jobserver-ui" "deployment" "labels" }}
    {{- $key }}: {{ $val | quote }}
  {{- end }}
{{- end -}}
{{- $labels := include "jobs-ui-deploy-labels" . -}}

{{- if $component.enabled -}}
apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ $fullName }}
  labels:
    app.kubernetes.io/name: {{ $name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "chart.chart" . }}
    {{- $labels | nindent 4 }}

spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ $name }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      {{- $labels | nindent 6 }}
  strategy:
    {{- toYaml $deploy.strategy | nindent 4 }}
  minReadySeconds: {{ $deploy.minReadySeconds }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ $name }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        {{- $labels | nindent 8 }}
    spec:
      containers:
        - name: jobs
          image: "{{ $image.repository }}:{{ $image.tag }}"
          imagePullPolicy: {{ $image.pullPolicy }}
          env:
            - name: NAMESPACE
              value: {{ $component.namespace  }}
            - name: REDIS_ADDR
              value: {{ $component.redisAddr | quote }}
          ports:
            - name: http
              containerPort: 80
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          {{- with $component.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with $component.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $component.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $component.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
