{{- $name := include "api.name" . -}}
{{- $fullName := include "api.fullname" . -}}

{{- if .Values.secrets -}}
apiVersion: v1
kind: Secret
type: Opaque

metadata:
  name: {{ $fullName }}
  labels:
    app.kubernetes.io/name: {{ $name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "api.chart" . }}

data:
{{- range $key, $val := .Values.secrets }}
  {{ $key }}: {{ $val | b64enc }}
{{- end }}
{{- end }}
