{{- $secrets := .Values.secrets -}}
{{- if not $secrets -}}
  {{- /* TODO: 'required' doesn't recognize empty maps */ -}}
  {{- required ".Values.secrets is required" .HACK -}}
{{- end -}}

apiVersion: v1
kind: Secret
type: Opaque

metadata:
  name: {{ include "api.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "api.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "api.chart" . }}

data:
{{- range $key, $val := $secrets }}
  {{ $key }}: {{ $val | b64enc }}
{{- end }}
