{{- $name := include "varnish.name" . }}
{{- $fullName := include "varnish.fullname" . }}
{{- $component := .Values.varnish }}
{{- $image := $component.image }}
{{- $storage := $component.storage }}
{{- $deploy := $component.deployment }}
{{- define "varnish-deploy-labels" }}
  {{- range $key, $val := .Values.varnish.deployment.labels }}
    {{- $key }}: {{ $val | quote }}
  {{- end }}
{{- end }}
{{- $labels := include "varnish-deploy-labels" . -}}

{{- if $component.enabled -}}
apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ $fullName }}
  labels:
    app.kubernetes.io/name: {{ $name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "chart.chart" . }}
    {{- $labels | nindent 4 }}

spec:
  replicas: {{ $deploy.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ $name }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      {{- $labels | nindent 6 }}
  strategy:
    {{- toYaml $deploy.strategy | nindent 4 }}
  minReadySeconds: {{ $deploy.minReadySeconds }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ $name }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        {{- $labels | nindent 8 }}
    spec:
      containers:
        - name: varnish
          image: "{{ $image.repository }}:{{ $image.tag }}"
          imagePullPolicy: {{ $image.pullPolicy }}
          args:
            - varnishd
            - -Ff
            - /usr/local/etc/varnish/default.vcl
            - -s
            - file,/var/lib/varnish/varnish_storage.bin,{{ .Values.varnish.storage.size }}
          volumeMounts:
            - name: config
              mountPath: /usr/local/etc/varnish/
            - name: storage
              mountPath: /var/lib/varnish/varnish_storage.bin
          ports:
            - name: varnish
              containerPort: {{ $deploy.port }}
              protocol: TCP
          {{- with $component.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ $fullName }}
        - name: storage
          hostPath:
            path: {{ $storage.hostPath }}
            type: FileOrCreate
      {{- with $component.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $component.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $component.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
