{{- $name:= include "chart.name" . }}
{{- $fullName := include "chart.fullname" . -}}

{{- if .Values.ingress.enabled }}
apiVersion: extensions/v1beta1
kind: Ingress

metadata:
  name: {{ $fullName }}
  labels:
    app.kubernetes.io/name: {{ $name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "chart.chart" . }}
  {{- range $key, $val := .Values.ingress.labels }}
    {{ $key }}: {{ $val | quote }}
  {{- end }}
  {{- with .Values.ingress.annotations }}
  annotations:
  {{- range $key, $val := . }}
    {{ $key }}: {{ $val | quote }}
  {{- end }}
  {{- end }}

spec:
{{- if .Values.ingress.tls }}
  tls:
  {{- range .Values.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
  {{- range .Values.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          {{- if .Values.ingress.path }}
          - path: {{ .Values.ingress.path }}
            backend:
          {{- else }}
          - backend:
          {{- end }}
              {{- if .Values.varnish.enabled }}
              serviceName: {{ include "varnish.fullname" . }}
              servicePort: varnish
              {{- else }}
              serviceName: {{ include "chart.fullname" . }}
              servicePort: api
              {{- end }}
{{- end }}
