{{- $name := include "jobs-ui.name" . }}
{{- $fullName := include "jobs-ui.fullname" . }}
{{- $service := .Values.jobserver.ui.service }}
{{- define "jobs-ui-service-labels" }}
  {{- range $key, $val := .Values.jobserver.ui.service.labels }}
    {{- $key }}: {{ $val | quote }}
  {{- end }}
{{- end }}
{{- $labels := include "jobs-ui-service-labels" . -}}

{{- if .Values.jobserver.ui.enabled }}
apiVersion: v1
kind: Service

metadata:
  name: {{ $fullName }}
  labels:
    app.kubernetes.io/name: {{ $name }}
    helm.sh/chart: {{ include "chart.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    {{- $labels | nindent 4 }}

spec:
  type: {{ $service.type }}
  ports:
    - name: http
      protocol: TCP
      port: {{ $service.port }}
  selector:
    app.kubernetes.io/name: {{ $name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    {{- $labels | nindent 4 }}
{{- end }}
