{{- $name:= include "varnish.name" . }}
{{- $fullName := include "varnish.fullname" . -}}
{{- $service := .Values.varnish.service }}
{{- define "varnish-service-labels" }}
  {{- range $key, $val := .Values.varnish.service.labels }}
    {{- $key }}: {{ $val | quote }}
  {{- end }}
{{- end }}
{{- $labels := include "varnish-service-labels" . -}}

{{- if .Values.varnish.enabled -}}
apiVersion: v1
kind: Service

metadata:
  name: {{ $fullName }}
  labels:
    app.kubernetes.io/name: {{ $name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "chart.chart" . }}
    {{- $labels | nindent 4 }}

spec:
  type: {{ .Values.service.type }}
  ports:
    - name: varnish
      protocol: TCP
      port: {{ $service.port }}
  selector:
    app.kubernetes.io/name: {{ $name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    {{- $labels | nindent 4 }}
{{- end }}
